name: Main workflow

on:
  #push:
  workflow_run:
    workflows: ["Dependent workflow"]
    types: 
      - completed

jobs:
  main-echo:
    runs-on: "ubuntu-latest"
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:

      - name: Main Checkout
        uses: actions/checkout@v4

      - name: Main Echo
        run: echo ok
