name: Main workflow

on:
  push:

jobs:
  main-echo:
    runs-on: "ubuntu-latest"
    steps:

      - name: Main Checkout
        uses: actions/checkout@v4

      - name: Main Echo
        run: echo ok
